language: go

go:
  - 1.14.x

env:
  - GO111MODULE=on

notifications:
  email: false

install:
  - curl -sL https://taskfile.dev/install.sh | sh
  - curl -sL https://releases.hashicorp.com/terraform/0.12.29/terraform_0.12.29_linux_amd64.zip -o terraform.zip
  - sudo unzip terraform.zip -d /usr/bin && rm -f terraform.zip
  - go install github.com/golang/mock/mockgen

script:
  - ./bin/task test build

deploy:
  - provider: releases
    api_key:
      secure: U0qhOhvd96fYNVZqIQ8neVqZUiF7FVY58ztIbWbgCKW+q+EwFqnT9yleOPeyhsl0TEvh6N0dYhvnu4vJdUNuLfrBl3g9M8rqyNqsGArJ3Pn1Rymipy5HzfonNcJtEThIBZefzrQcnmMnjJlr8SRZ5JAv0xmiEJshBq3G30sG9+0AbmR33yJXy++uLFyuqHDzrpih4mB8+yTg5wuv4994q33L2fNZbcN6efOJ49nMjnR6tXNzuz7ZzNonHJO1Z4adZHvq/awA3Si0EMZb2x5dQmGQTEDiMiwTnqLSkrQG97zai3MywSPDVOsChZldis6Qu6OADeRLVmRIBypVaK1a5PmsVOZJCOnoeXDVY3WuK4hG5CavP+wvyjNOR/r2Zvu5QgNXGlfNh+O3RUI8yoqUS4Dhg0PuWJRjrlCh0zaUssNMVbJgWAKjHWKRXW4lgUP8HzzLUY2gk0LkAgb6TJf0KWvulQmcRHuzV274MrL1FHTln3fncODvVw3r6PROjQ7JIe3YZXDPawNs8rebSaEAMnRNyolEdMew1nP/lo/9FQt5L5DUBQ0yMVZfaXvnx4Dui8PKAsMTNBwZuXS5hFqoa8LBzoRcRB0yP6tLKIMoXe5k1B+D8GVtOD2J4sgbXWOH6gPho1Q3dit33UOXenKA2lcJVsXH94XGmI1L/K6+tHk=
    file: build/concourse-github-lambda.zip
    skip_cleanup: true
    on:
      repo: telia-oss/concourse-github-lambda
      tags: true

  - provider: s3
    access_key_id: AKIAIXXEON53QC2UQBPA
    secret_access_key:
      secure: JIboEjMPFam09m6bXXLrdC7wiXIwFJxo7czcs4zvTwkQYYQIBbU1urCOR88IcPAkYWkIzd1sN4lsQbd7Z0OvZpJLVPS1tIEBVnKwDotA4fzpFbFDzVx7V4Q8/T3Gaptx+IzZA8aUFop2phyaW6v6WOHqWv0oSEoBT86Dt4DmjokFfMNqeppoH5vNnEtus5lNoRF3l3DvLrKklRw1pR2dcROifOLKQRsa/C531Uc0O5dNzicNeiYQaSoNWmC1Snu6x1W0VfEEgkE7MshuoHzpFCSkj4aSecj9+83jw44EmUNrVI5PdWp1FSzrY3NeRX8VNeAAe1HI7OblAHPEm+Yp3gqpG/czuwy+bRNYu/J8V8FHfLDuLUUqZA7aU2qrx9i2u0P8VjNc0H9nECD8TxmK393Cw4YMDErt3IxG/CrA8zSboLsCVRy/ligaf4Ykvr7QIQoERsNhgQ7dpOva07ykVrW7UIm/olpQoXki8FmKTsENQPqir33N7x0hpju+Ag8D93bGyEiZa1H9vBOpLXEn6AT60dVNKBN/PR59Zhey/MW72iOsO0G+Smur8+9buQnQ+YsPNvHVPqD6PbS9PnokjPngjNd28tZBOug9e0mt0UOE6fJVmtu1Bbq10I/tl6OqveUf/uI9DGZWLh58F7Z9gj87U7ihKCk0hY+h24HxMDs=
    bucket: telia-oss
    region: eu-west-1
    local-dir: build
    upload-dir: concourse-github-lambda
    acl: public_read
    skip_cleanup: true
    on:
      repo: telia-oss/concourse-github-lambda
      tags: true
